### PR TITLE
Add AbstractPunishment.java and have Mute.java and Ban.java both extend it.

### PR DESCRIPTION
**Pull request by Jake-SA**
Commit msg: Add AbstractPunishment.java; modify Mute.java, Ban.java.

Doing this will generalize a punishment so it can be iterated later, for example, or so that it can be referred to in a generic sense.

### CODE REVIEW

**Comment by HMCJake** [comment]
I believe the TCI build failed due to master failing.

**Comment by Fireflies** [comment]
master needs a tiny bit of work :tongue:
going to be sitting down and looking through all my projects that need fixes this weekend

**Comment by Jake-SA** [comment]
Cool, sounds good. Can't wait to see this project progress.

**Comment by Fireflies** [comment]
@Jake-SA
Just wanted to let you know I haven't forgot about this, the wifi at the site I'm staying at is horrific!

`git clone` is basically useless (fails 80% of the time) :(

**Comment by Fireflies** [comment]
@Jake-SA, another update! (You must be getting sick of seeing my name appear in your notifications!)

I've been contracted to work on another ban plugin (an entirely modular rewrite of BungeeAdminTools) with a great and robust API that even allows for custom modules (loaded via the plugin, not the server plugin system)

If at the end of my contract I am permitted to share this project then it will take the place of this repository, otherwise I shall return to writing Sukibans :smile:

**Comment by Jake-SA** [comment]
Heh, alright. Have fun with that, then.

**Pull request merged**
